repos:
- repo: https://github.com/python-poetry/poetry
  rev: '2.1.2'
  hooks:
  -   id: poetry-check
  -   id: poetry-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    - id: mypy
      language: system
      entry: poetry run mypy
      pass_filenames: false
      args: ["--config-file=pyproject.toml", "."]